sudo: required
dist: trusty
language: python
services:
- docker
install: true
script:
- "./build.sh"
notifications:
  slack:
    template:
    - Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository_slug}@%{branch}>
      by %{author} %{result} in %{duration}
    - 'Image Name: readytalk/turn-docker:3.2.%{build_number}-%{commit}'
    on_success: always
    on_failure: always
    rooms:
      secure: BHY07LYF8GF4EbDhWq0Z3o3/TI7bg1hPz9Xvf7jhExUc10euHC8GMt4gO5Nb920INaw31s/V7Dsh4X+glif49F/PRWDOtPx20Ii/BX0ANsAlAuKfqu5ft5H3t4MZZbyUUwK7Zqye8wOShGucZgYdHXeHnSHb9V9jskopIqGFKUI2kSCdYEze3OQAghcB+xqZ89JYSYLyihwVj+JkaAjOvZqcBtvyLwy27FCOY26g9pHMQWd2teGMC81lGKGzPqBAAsUu2hpxZVcQ4s2zzMxc0SbMsDxAWUCdpb6WRTdtpBTzG5X8xLf/4AfEjgGAMUc+ANTC/Z0jQRUl5HjEBuHZv9zhCVbVqSi78o/Hmd+um+xpd3U7X7L2zMmeEDIAWce6GExgW7H/byFSILXB9KpNiU4jdr7c0h26bwCyd2CCfqw6d0B1GQy6/cRzjZs9OrKEM8CWjAtgmqnGyyrCxw4Puj77M9JD26+iAZ7Vb0i+UxPweorr1NVkkRSkvK8g3/EqCJFrkYL/ewfKymWcJe2eA2yedxfSJ5vJCgLLWFOdC85NCZrB4emtxLNZhPbpEWDAbNcIuCsOWlUR4963YL1LdoeXPP2KD05kQoWLE4149aRISMarclaEO3wi6iznyTCN/4lOR7x8R7zUCiqlgfXJ2jaHmPXCac5cN2v78IKHTb0=
env:
  global:
  - secure: OYySbXzS07VKvwPxvORT7N3a1416GKUXRtxHUIDnneDGzQwXBVE9t/YkKBYUeUi+Nmom7q4sqk6eZRT715GbFzS1JplHPxstXvt37izYasj13jdEuPBuz4ExTlMBY56qsLJSVMQtY8IFQl/uzF6V3Zbb2I/JvMbJTYrreEqQ39a34cRELOKt5qgX9xTsJKzwIHOdxAiofQhAGaQ6F+e3Q7yG8nDYjbsf7ZOLzKwPrxiaoqYc8Y9383KQBXKqpp6OQOVKjQx3SiUPXO+rhEnZNfbvNBeeNWf1WKLmNqxOmLcF6n8opk1o+dkjgwa3nG08qBjLPsVZEBB0sevsKaSSlJYrAP3abrcgIwRjEDIZCnB8/4RdAaYPCgyZ5+dRwKNeSHHiKIm7aKMMGf7JmXY8Xel0qj/ozFs7rhkXLXI2pYpzRVv5FoE2WZQhlnfwR/GoHD4dQT2zHebKKZlzY62+b5mGFULQCRahhbFyF0liDJoG4xc9o7IPL2rJkz+z8Cy9AVr3HwjZi6fnWXkz2NE+VmPhrWkV7KOXGrGb+dOum8IwNQSyzbpEPMnU2tDkHtXeTSIOYjvMp1RRK84Ku54VKVBg9gzJ7PHqdv9DAfUdxdNtLAbacpdO6dDrJ4CvjlRU4W79GV8+0XpUr9lP4tPE8GePkqI5LS8mXOEyPj2Swtw=
  - secure: r6Rg4eEAX9kr7If467hTUsXUuX5ZDwN+JGSKaGdzM807uuk/hEdeB1Pea9/AcdV7HQVFbShAeln4Nos/daT6T+V4kR9dmMxRgk4GotHfeP5rkp9j2gO3PdFbvElUK3ONZQgunf+5W4ezqEqZEW7UJ9A55+2foGxequAQxk93cXSq/oWlduhJk0dyIu7H29jnGn6PXKO9Wa1NI9qB5uRglZP3a5PZeLHLGijdmHMy6cFUNz94hQb2t8a4hIHbzwDa7zsxIpzAAcNrLOqcKANiyRTXCkPNoK/bRJChaVmY/O65sCq9918Gtg+E7GPRSPML79DmBZ1CpKsv+RsKbVkbMJWtlbX7NDf5PmZ9u8djWbNGkJiJrSQMG7lRg6lfL4rv9NJqqud5hlv2dBCfh+LUuYt4NtLeDlLHzkWJ/Qbu4w86uMrc0SB/4TNibAOVIRff2889yljXpSNf8QQMm/UlpxUw1vYoUWBxeF1APOwl3TqsfJsMqpDvmk8+CsC1+jNirpvl9cF96RRIc9V34vTMJY5pJLAjouU2xih0bXbG82DtTptCgWUGySK5yswKi6LScHnxpUQJ3ZROFOsZJ8J3r1P2j+ItJv0oxYaDgxISrEAz4JRyHHcZqfRkLoSp/8pB2mdandwJAOwbMjBVAoFBwdB+r4MrbdHMppZz+mTIc70=
